0824_RPA/RPA/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
urlpatterns = [
	path('admin/', admin.site.urls),
	path('',include('main.urls',namespace='main')),

]

0824_RPA/main/urls.py
from django.urls import path
from main import views

# SET THE NAMESPACE!
#Globle name
app_name = 'main'

urlpatterns=[
	path('',views.index,name='index'),
	path('introduction/',views.introduction,name='introduction_2'),
	path('introduction_demo/',views.introduction_demo,name='introduction_demo'),
	path('tool',views.Tool_View.as_view(),name='tool'),
	path('contect_us/',views.contect_us,name='contect_us'),
]

0824_RPA/main/models.py
from django.db import models

# Create your models here.

0824_RPA/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseBadRequest, HttpResponse
from django.views import View
from django.template.loader import render_to_string
def index(request):
    return render(request,'main/index.html')

def introduction(request):
    return render(request,'main/introduction_2.html')

def contect_us(request):
    return render(request,'main/contect_us.html')

def introduction_demo(request):
    return render(request,'main/introduction_demo.html')


# tot_dose = [ [0.0 for m in range(15)] for y in range(10)]
def cal_dose(index):
	tot_dose = [ [ 0.0 for m in range(15)] for y in range(10)]
	# print(index)
	tot_dose[0][0] = int(index['1_1'])*1.41
	tot_dose[0][1] = int(index['1_2'])*2.42
	tot_dose[0][2] = int(index['1_3'])*7.09
	tot_dose[0][3] = int(index['1_4'])*8.12
	tot_dose[0][4] = int(index['1_5'])*16.31
	tot_dose[0][5] = int(index['1_6'])*10.83
	tot_dose[0][6] = int(index['1_7'])*22.10
	tot_dose[0][7] = int(index['1_8'])*7.46
	tot_dose[0][8] = int(index['1_9'])*3.47
	tot_dose[0][9] = int(index['1_10'])*3.22
	tot_dose[0][10] = int(index['1_11'])*20.09

	tot_dose[1][0] = int(index['2_1'])*5.27
	tot_dose[1][1] = int(index['2_2'])*10.36
	tot_dose[1][2] = int(index['2_3'])*16.55
	tot_dose[1][3] = int(index['2_4'])*3.7
	tot_dose[1][4] = int(index['2_5'])*11.1
	# tot_dose[1][5] = int(index['2_6'])*10.83

	tot_dose[2][0] = int(index['3_1'])*12.71
	tot_dose[2][1] = int(index['3_2'])*54.35
	tot_dose[2][2] = int(index['3_3'])*5.2
	tot_dose[2][3] = int(index['3_4'])*4.56
	tot_dose[2][4] = int(index['3_5'])*69.66
	# tot_dose[2][5] = int(index['3_6'])*10.83

	tot_dose[3][0] = int(index['4_1'])*0.087
	tot_dose[3][1] = int(index['4_2'])*29.43
	tot_dose[3][2] = int(index['4_3'])*7.65
	tot_dose[3][3] = int(index['4_4'])*5.63
	tot_dose[3][4] = int(index['4_5'])*4.02
	# tot_dose[3][5] = int(index['4_6'])*10.83

	tot_dose[4][0] = int(index['5_1'])*3
	tot_dose[4][1] = int(index['5_2'])*8
	tot_dose[4][2] = int(index['5_3'])*6
	tot_dose[4][3] = int(index['5_4'])*6
	tot_dose[4][4] = int(index['5_5'])*6
	tot_dose[4][5] = int(index['5_6'])*1.2
	# tot_dose[4][6] = int(index['5_7'])*22.10


	tot_dose[5][0] = int(index['6_1'])*0.04
	tot_dose[5][1] = int(index['6_2'])*0.13
	tot_dose[5][2] = int(index['6_3'])*0.92
	tot_dose[5][3] = int(index['6_4'])*0.38
	tot_dose[5][4] = int(index['6_5'])*1.15
	tot_dose[5][5] = int(index['6_6'])*0.003
	# tot_dose[5][6] = int(index['6_7'])*22.1

	tot_dose[6][0] = int(index['7_1'])*0.39
	tot_dose[6][1] = int(index['7_2'])*0.59

	tot_dose[7][0] = int(index['8_1'])*0.0039
	tot_dose[7][1] = int(index['8_2'])*0.0057
	tot_dose[7][2] = int(index['8_3'])*0.0016
	tot_dose[7][3] = int(index['8_4'])*0.013
	tot_dose[7][4] = int(index['8_5'])*0.017
	tot_dose[7][5] = int(index['8_6'])*0.0022

	for i in range(8):

		# python tuple
		tot_dose[8][i]=round(sum(tot_dose[i]),3)
		tot_dose[9][0] = round(tot_dose[9][0]+sum(tot_dose[i]),4)
	# print('From cal_dose**************************')
	# print(tot_dose)
	# print(sum(tot_dose[0]))
	return tot_dose

from django.shortcuts import render

from plotly.offline import plot
import plotly.graph_objs as go

class Tool_View(View):
	template_name = 'main/tool.html'
	def __init__(self):
		super().__init__()

	def get(self, request):
		times_list = []
		for times in range(1,11):
			times_list.append(times)
		list_context = {'times_loop': times_list}
		return render(request, self.template_name,list_context)

	def post(self, request):
		times_list = []
		for times in range(1,11):
			times_list.append(times)
		list_context = {'times_loop': times_list}


		if request.method == "POST":
			tot_dose = cal_dose(request.POST)
			sum_dose=[ () for p in range(8) ]
			label_name = ['電腦斷層', '核子醫學', '心臟類攝影', '非心臟類攝影', '傳統透視攝影', '一般傳統X光', '乳房攝影', '牙科攝影']
			for t in range(8):
				sum_dose[t]=(tot_dose[8][t], label_name[t])

			sum_dose = (sorted(sum_dose, key = lambda sum_dose: sum_dose[0], reverse=True) )
			# sum_dose2 = (sorted(sum_dose, key = lambda sum_dose: sum_dose[0], reverse=True) )
			# tot_dose[8] = sorted( tot_dose[8], key = lambda tot_dose[8] : tot_dose[8][1])
			print(sum_dose)
			dose_quantity = []
			# dose_quantity2 = []
			for u in range(8):
				dose_quantity.append(sum_dose[u][0])
				# dose_quantity2.append(sum_dose2[u][0])
			xlabel=[]
			for k in range(8):
				xlabel.append(sum_dose[k][1])
			print(dose_quantity)
			sunflowers_colors = ['#f7e731', '#F4A7B9', '#E16B8C', '#66BAB7','#9B90C2', '#A5DEE4','#A8497A','#4E4F97']
			# sunflowers_colors_2 = [ '#4E4F97','#A8497A','#A5DEE4','#9B90C2', '#66BAB7','#E16B8C','#F4A7B9','#f7e731',]
			hist_data=(go.Histogram(
					x=dose_quantity,
					y=xlabel,
					histfunc="sum",
					name='experimental',
					xbins=dict(
						size=0.5,
						),
					marker_color=sunflowers_colors,
					opacity=0.75,
					orientation='h',

			))
			annotations = []
			for  yd, xd in zip( xlabel, dose_quantity):
				annotations.append(dict(xref='x1', yref='y1',
					y=yd, x=xd,
					text='                      '+str(xd)+' mSv',
					font=dict(family='Arial', size=14,
						color='#000000'),
					showarrow=False
				))
			hist_layout = go.Layout(
				# xaxis = {'title':'劑量 (毫西弗mSv)','showgrid':True,},
				template="xgridoff",
				# paper_bgcolor='rgba(0,0,0,0)',
				# plot_bgcolor='rgba(0,0,0,0)',
				xaxis=dict(
					showticklabels=False,
					side="top",
					# title='劑量 (毫西弗mSv)',
				),
				yaxis=dict(
					# showticklabels=False,

					# categoryorder='total ascending'
				),
				# yaxis = {'title':'項目', 'categoryorder':'total ascending'},
				bargap=0.2, # gap between bars of adjacent location coordinates
				bargroupgap=0.2, # gap between bars of the same location coordinates
				annotations=annotations
			)
			plot_hist = plot( {'data':[hist_data], 'layout':hist_layout }
			, auto_open=False, output_type='div', image_height=0.1)



			# sunflowers_colors = ['#F4A7B9', '#E16B8C', '#66BAB7','#9B90C2', '#A5DEE4','#A8497A','#4E4F97']
			plot_div = plot([go.Pie(labels=xlabel, values=dose_quantity,textinfo='none', name="劑量計算結果",marker_colors=sunflowers_colors )], auto_open=False, output_type='div',  image_height=0.1 )

			re_list = {'1th': tot_dose[8][0], '2th': tot_dose[8][1], '3th': tot_dose[8][2], '4th': tot_dose[8][3],'5th': tot_dose[8][4], '6th': tot_dose[8][5],  '7th': tot_dose[8][6], '8th':tot_dose[8][7], 'total_dose': tot_dose[9][0], 'plot_div': plot_div, 'plot_hist': plot_hist}
			rendered = render_to_string('main/response_user.html', re_list)
			return HttpResponse(rendered)

		return render(request, self.template_name,list_context)

0824_RPA/main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html>

<head>
	<meta charset="utf-8">
	<title>RPA</title>
	<link rel="stylesheet" href="{% static "main/css/bootstrap.min.css" %}">

	<!-- <script src="{% static "main/js/bootstrap.bundle.js" %}" type="text/javascript"></script> -->
	<!-- <script src="{% static "main/js/bootstrap.js" %}" type="text/javascript"></script> -->
	<script src="{% static "main/js/jquery.min.js" %}" type="text/javascript"></script>

	<!-- <script	src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
	integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
	crossorigin="anonymous"></script> -->



	<link rel="stylesheet" href="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/css/bootstrap.min.css">

	<script src="https://cdn.staticfile.org/jquery/2.1.1/jquery.min.js"></script>

	<script src="https://cdn.staticfile.org/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>


	<link href="https://fonts.googleapis.com/css?family=Blinker|Roboto&display=swap" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Merriweather&display=swap" rel="stylesheet">
	<link rel="icon" href="{% static "main/images/rpa.ico" %}" type="image/x-icon">
	<link href="https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@600&display=swap" rel="stylesheet">

	<link rel="stylesheet" href="{% static "main/css/main.css" %}">
	<!-- <link rel="stylesheet" href="{% static "main/css/main_en.css" %}"> -->
	<script src="{% static "main/js/main.js" %}" type="text/javascript"></script>
	<!-- <link rel="stylesheet" href="{% static "main/css/bootstrap.min.css" %}"> -->


</head>

<body>
	<div class="container" >

		<nav class="navbar navbar-expand-sm navbar-light bg-light">
			<a id="chlang" class="navbar-brand" href="{% url 'main:index' %}">首頁</a>
			<div class="collapse navbar-collapse" id="navbarNav">
				<ul class="navbar-nav mr-auto ">

					<li id="chlang" class="nav-item">
						<a class="nav-link" href="{% url 'main:introduction_2' %}">簡介</a>
					</li>

					<li id="chlang" class="nav-item">
						<a class="nav-link" href="{% url 'main:tool' %}">醫療劑量計算</a>
					</li>
					<li id="chlang" class="nav-item">
						<a class="nav-link" href="{% url 'main:contect_us' %}">聯絡我們</a>
					</li>
				</ul>
			</div>
			<!-- <button class="btn btn-light my-2 my-sm-0" type="submit">Sign in</button> -->

		</nav>
		{% block body_block %}
		{# Anything outside of this will be inherited if you use extend.#}
		{% endblock %}
	</div>
</body>

</html>

0824_RPA/main/templates/main/contect_us.html
<!DOCTYPE html>

{% extends "main/base.html" %}
{% load static %}
{% block body_block%}
<script>
	//宣告預設表單內容為空 （你想要的話也可以加東西）
	var initSubject = '',
		initBody = '';

	//按下傳送按鈕後執行
	function submitHandler() {
		var to = "tim131lee@gapp.nthu.edu.tw";
		var name = nameText.value;
		var email = emailText.value;
		var tel = telText.value;
		var subject = subText.value;
		var body = "" + bodyText.value + '%0A%0A%0A';
		body += "From：" + nameText.value + '%0A';
		body += "Email：" + emailText.value + '%0A';
		body += "Tel：" + telText.value;
		mailTo.href = "mailto:" + to + "?subject=" + subject + "&body=" + body;
		mailTo.click();
	}

	function init() {
		subText.value = initSubject;
		toText.value = initTo;
		bodyText.value = initBody;
	}
</script>

<div class="jumbotron">
	<div class="row no-gutters">

		<div class="card col-12">
			<div id="background_1" class="card-header">
				<div id="header_1">
					<h3 id="text_1" class="row justify-content-md-center" style="font-size: 2.7rem;"> <strong>聯絡我們</strong> </h3>
				</div>

				<div class="card-body">
					<h4 id="text_0" class="row justify-content-md-center"style="text-align:center;">
						請將您的寶貴意見以填寫訊息的方式送出，我們將於工作日由專人以郵件回復您的問題<br>
						地址：新竹市東區光復路二段295號15樓之一<br>
						電話：03-5722224<br>
						Email：rpa@ms9.hinet.net<br>
					</h4>
				</div>
			</div>
		</div>
		&nbsp;
		<!-- <form class="col col-12" enctype="text/plain" accept-charset="utf-8">
			<div class="card">
				<div class="card-header">
					<p id="header_1">個人資訊</p>
				</div>
				<div class="card-body justify-content-md-center">
					<div class="row col-12 justify-content-md-center">

						<div class="input-group col col-lg-6 col-sm-12">
							<input id="nameText" name="Name" type="text" class="form-control" placeholder="姓名(name)" aria-label="Username" aria-describedby="basic-addon1" required>
						</div>
						<div class="input-group col col-lg-6 col-sm-12">
							<input id="telText" name="Phone" type="tel" class="form-control" placeholder="電話(phone)" aria-label="Userphone" aria-describedby="basic-addon1" required>
						</div>
						<p></p>
						<div class="input-group col-12">
							<input id="emailText" type="email" name="Email" class="form-control" placeholder="Your Email" aria-describedby="basic-addon1" required>
						</div>
					</div>
				</div>
			</div>

			<div class="card">
				<div class="card-header">
					<p id="header_1">留言資訊</p>
				</div>
				<div class="card-body">
					<div class="input-group col col-lg-12 col-sm-12">
						<input id="subText" type="text" name="Subject" rows="2" class="form-control" placeholder="主旨(subject)" aria-describedby="basic-addon1" required>
					</div>
					<div class="input-group">
						<textarea id="bodyText" name="your-message" class="form-control" aria-label="With textarea" aria-required="true" aria-invalid="false" placeholder="你的訊息(Your Message)" rows="10" required></textarea>
					</div>
					<div>
						<input class="btn btn-light btn-lg" type="button" value="送出訊息" onclick="submitHandler()">
						<a id="mailTo"></a>
					</div>

				</div>
			</div>


		</form> -->

	</div>
</div>
{% endblock %}

0824_RPA/main/templates/main/index.html
<!DOCTYPE html>

{% extends "main/base.html" %}
{% load static %}
{% block body_block%}
<div class="jumbotron">
	<div class="row no-gutters">
		<!-- <div class="col-lg-3">
                 <img src="{% static "main/images/LOGO1.PNG" %}" class="card-img" alt="...">
             </div> -->
		<div class="card col-lg-12">
			<div id="background_1" class="card-header">
				<div id="header_1" style="border-bottom: 2px solid rgb(0, 0, 0, .2); ">
					<h3 id="text_1" class="row justify-content-md-center" style="font-size: 2.7rem;"> <strong>中華民國輻射防護協會</strong> </h3>
				</div>
				<div id="orth_re_text" class="card-body m-3">
					<h4 id="text_1" class="row justify-content-md-center">國立清華大學原子科學院、行政院原子能委員會、核能研究所、台灣電力公司等機構之學者專家，有鑑於長久以來輻射在社會上引起了各種問題，如環境、健康、法律等問題急待解決，乃發起籌組輻射防護協會，以期結合各界之力量，從客觀立場貢獻心力。</h4>
				</div>
			</div>
		</div>
		&nbsp
		<div class="card col-12">
			<div class="card-header">
				<div id="text_1" class="card-body" style="border-bottom: 2px solid rgb(0, 0, 0, .2); ">
					<h4 id="text_1" class="row justify-content-md-center">輻協為非營利性之組織，其目的為協助政府及民間提昇輻射防護專業知識及技術，促進公眾與環境輻射安全。
						<br> 主要業務如下：<br>
						1. 提供有關輻射防護之評估、諮詢及技術服務。<br>
						2. 人員體外輻射劑量評估服務。<br>
						3. 從事有關輻射防護之研究發展。<br>
						4. 辦理輻射防護相關之訓練及學術研討會。<br>
						5. 推動國內、外有關機構之學術交流合作，提昇輻射防護科技之應用。<br>
						6. 出版輻射防護教材、刊物、技術手冊、通識手冊及輻防簡訊等。<br>
						7. 辦理其它有關輻射防護之業務。<br>

					</h4>
				</div>
				<div class="col col-12" id="header_1" style="border-bottom: 2px solid rgb(0, 0, 0, .2); ">
					<h3 id="ch_read" style="text-align:center; font-size: 2.0rem;">
						財團法人中華民國輻射防護協會<br>
						地址：新竹市東區光復路二段295號15樓之一<br>
						電話：03-5722224<br>
						Email：rpa@ms9.hinet.net<br>
					</h3>
				</div>

			</div>
		</div>
	</div>
</div>




{% endblock %}

0824_RPA/main/templates/main/introduction_2.html
<!DOCTYPE html>

{% extends "main/base.html" %}
{% load static %}
{% block body_block%}
<!-- <div id="myFirstchart-container">{{ output|safe }}</div> -->

<div class="jumbotron">
	<div class="row no-gutters">
		<div class="card col-12">
			<div id="background_1" class="card-header">
				<div id="header_1">
					<h3 id="text_1" class="row justify-content-center" style="font-size: 2.7rem;"> <strong>國民醫療輻射劑量評估系統</strong> </h3>
				</div>

				<div class="card-body">
					<h4 id="text_0" class="row justify-content-center"> &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp國民劑量的輻射曝露來源有二：天然背景輻射與人造輻射，而人造游離輻射劑量中，對民眾貢獻來源最大的是來自醫療曝露(NCRP,
						2009)。自一世紀前發現放射核種和X光，游離輻射很快地被用於醫學上，現在已被確立為醫學診斷和治療的必要工具。過去幾十年間，因醫療影像設備與成像技術快速發展，使得醫用X光成像和核子醫學成像的使用率顯著增長，無論在歐洲，美國還是台灣都有類似的增長趨勢，今年透過分析健保資料庫的醫療輻射檢查的案件數，發現台灣的平均成長率最高到達8.2%。<br></h4>
					<h4 id="text_0" class="row justify-content-center">
						&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp醫療輻射類別的統計數據是衡量國家放射學與醫療水準的全球指標，因為其反應出醫療體系、放射學設備和人力配置的差異，而開發程度不同的國家，其各自醫療曝露劑量差異也很大。在一份研究統計報告比較全球醫療水準較高和較低的國家，其醫療曝露的國民平均年劑量分別為每人每年1.1和0.05 mSv (HPS, 2009)。由於不同國家的醫療曝露劑量差異很大，歐盟資助的計畫(Dose
						DataMed)確定了這些差異的存在原因，不單是民眾醫療輻射檢查次數的差異，也來自於相同的檢查操作條件設定也不盡相同(Bly, 2011)。<br></h4>

					<h4 id="text_0" class="row justify-content-center">
						&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp透過全民健康保險研究資料庫取得醫療作業項目頻次，若有檢查項目未涵蓋於全民健康保險研究資料庫的部分則需配合其他相關資料庫以補足。另需透過實地調查醫療作業中的醫療輻射作業檢查項目、技術條件設定、臨床實際掃描方法等資訊，計算彙整出不同類別醫療輻射的檢查項目輻射劑量，再以實地量測方式：包括射質評估、劑量輸出測量以確定劑量評估的準確性，藉由此次調查研究，了解醫療輻射造成台灣整體國民輻射劑量之情形，建立完整的國民醫療輻射劑量資料，未來亦可利用此資料評估國民醫療輻射運用的變化趨勢。<br>
					</h4>
				</div>
			</div>
		</div>
		&nbsp
		<div class="card col-12">
			<div id="text_0" class="card-body " style="border-bottom: 2px solid rgb(0, 0, 0, .2); ">
				<h4 id="text_0" class="row ">執行國民醫療輻射劑量評估調查，經過醫療院所與健保資料庫取樣後完成下列8種醫療輻射類別。共46個檢查項目劑量評估，包含檢查項目如下：</h4>
				<div class="card-group ">
					<div class="card col-3 ">
						<div class="card-body ">
							<h3 id="header_1" class=" row justify-content-lg-center ">一般傳統X光</h3>
						</div>
					</div>
					<div class="card col-9">
						<div class="card-body">
							<h4 id="text_1" class="row">
								包含頭頸部、胸肩部、腹部(含骨盆腔)、腎臟-輸尿管-膀胱、脊椎、四肢，共6項。</h4>
						</div>
					</div>
				</div>
				<div class="card-group ">
					<div class="card col-3">
						<div class="card-body ">
							<h3 id="header_1" class=" row justify-content-lg-center ">乳房攝影</h3>
						</div>
					</div>
					<div class="card col-9 ">
						<div class="card-body ">
							<h4 id="text_1" class="row  ">
								包含一般乳房攝影、穿刺前攝影，共2項。</h4>
						</div>
					</div>
				</div>

				<div class="card-group">
					<div class="card col-3">
						<div class="card-body ">
							<h3 id="header_1" class=" row justify-content-lg-center ">牙科攝影</h3>
						</div>
					</div>
					<div class="card col-9">
						<div class="card-body">
							<h4 id="text_1" class="row ">
								根尖周、咬翼式、咬合片、齒顎全景、測顱、顳顎關節(單側)，共6項。</h4>
						</div>
					</div>
				</div>

				<div class="card-group">
					<div class="card col-3">
						<div class="card-body ">
							<h3 id="header_1" class=" row justify-content-lg-center ">傳統透視攝影</h3>
						</div>
					</div>
					<div class="card col-9">
						<div class="card-body">
							<h4 id="text_1" class="row ">
								包含靜脈注射泌尿系統造影術、下消化道攝影、上消化道攝影、食道攝影、小腸系統、子宮輸卵管造影，共6項。</h4>
						</div>
					</div>
				</div>

				<div class="card-group">
					<div class="card col-3">
						<div class="card-body ">
							<h3 id="header_1" style="text-align: center" class=" row justify-content-lg-center ">
								非心臟類<br>介入性透視攝影</h3>
						</div>
					</div>
					<div class="card col-9">
						<div class="card-body">
							<h4 id="text_1" class="row ">
								包含血管整形術、血管阻塞術、經皮穿肝膽管引流術(含修正術)、皮下穿刺腎造廔術、逆行性膽道及胰管造影，共5項。</h4>
						</div>
					</div>
				</div>

				<div class="card-group">
					<div class="card col-3">
						<div class="card-body ">
							<h3 id="header_1" style="text-align: center" class=" row justify-content-lg-center ">
								心臟類<br>介入性透視攝影</h3>
						</div>
					</div>
					<div class="card col-9">
						<div class="card-body">
							<h4 id="text_1" class="row ">
								包含一、二側心導管與冠狀動脈攝影、冠狀動脈擴張術(含血管內/心臟內異物移除術)、心室、主動脈造影、不整脈經導管燒灼術、主動脈氣球裝置術，共5項。</h4>
						</div>
					</div>
				</div>


				<div class="card-group">
					<div class="card col-3">
						<div class="card-body ">
							<h3 id="header_1" class=" row justify-content-lg-center ">電腦斷層</h3>
						</div>
					</div>
					<div class="card col-9">
						<div class="card-body">
							<h4 id="text_1" class="row ">
								包含頭部、頸部、胸部、上腹部、腹部(含骨盆腔)、胸部與上腹部、胸部與腹部(含骨盆腔)、骨盆、下肢、脊椎、心血管，共11項。</h4>
						</div>
					</div>
				</div>

				<div class="card-group">
					<div class="card col-3">
						<div class="card-body ">
							<h3 id="header_1" class=" row justify-content-lg-center ">核子醫學</h3>
						</div>
					</div>
					<div class="card col-9">
						<div class="card-body">
							<h4 id="text_1" class="row ">
								包含全身骨骼掃描、壓力與重分佈心肌斷層灌注掃描、正子造影-全身、心室搏出分率及心室壁活動測定、全身炎症掃描，共5項。</h4>
						</div>
					</div>
				</div>
				<div id="text_1" class="card-body">
					<div class="row justify-content-center">
						<button class="btn btn-secondary btn-lg" type="button" onclick="printpage()">
							另存相關資訊
						</button>
					</div>
				</div>
			</div>
			<div class="col col-12" id="header_tool">
				<h5 id="ch_read" style="text-align: center;  font-size: 1.0rem;">
					Copyright © 2021 財團法人中華民國輻射防護協會.
					</h3>
			</div>
		</div>
	</div>
</div>
{% endblock %}